`len(vitalPeriodic) = 146671642`

In [38]:
from src.preprocessing import *

patient = get_df("patient")
patient

,patientunitstayid,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,wardid,apacheadmissiondx,admissionheight,hospitaladmittime24,...,unitadmitsource,unitvisitnumber,unitstaytype,admissionweight,dischargeweight,unitdischargetime24,unitdischargeoffset,unitdischargelocation,unitdischargestatus,uniquepid
0,141168,128919,Female,70,Caucasian,59,91,"Rhythm disturbance (atrial, supraventricular)",152.4,15:54:00,...,Direct Admit,1,admit,84.3,85.8,03:50:00,3596,Death,Expired,002-34851
1,141178,128927,Female,52,Caucasian,60,83,NaN,162.6,08:56:00,...,Emergency Department,1,admit,54.4,54.4,09:18:00,8,Step-Down Unit (SDU),Alive,002-33870
2,141179,128927,Female,52,Caucasian,60,83,NaN,162.6,08:56:00,...,ICU to SDU,2,stepdown/other,NaN,60.4,19:20:00,2042,Home,Alive,002-33870
3,141194,128941,Male,68,Caucasian,73,92,"Sepsis, renal/UTI (including bladder)",180.3,18:18:40,...,Floor,1,admit,73.9,76.7,15:31:00,4813,Floor,Alive,002-5276
4,141196,128943,Male,71,Caucasian,67,109,NaN,162.6,20:21:00,...,ICU to SDU,2,stepdown/other,NaN,63.2,22:23:00,1463,Floor,Alive,002-37665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200854,3353235,2743084,Male,50,Caucasian,458,1109,"CHF, congestive heart failure",175.3,04:55:00,...,Emergency Department,1,admit,90.0,99.2,23:18:00,1069,Telemetry,Alive,035-16382
200855,3353237,2743086,Female,79,Caucasian,458,1106,"Embolus, pulmonary",162.6,01:45:00,...,Direct Admit,1,admit,78.4,81.4,23:08:00,1269,Step-Down Unit (SDU),Alive,035-751
200856,3353251,2743099,Male,73,African American,458,1104,Cardiac arrest (with or without respiratory ar...,177.8,12:51:00,...,Emergency Department,1,admit,102.0,96.2,23:16:00,16259,Telemetry,Alive,035-5166
200857,3353254,2743102,Male,81,Caucasian,459,1108,"Bleeding, lower GI",185.4,07:43:00,...,Emergency Department,1,admit,83.9,92.9,19:25:00,431,Step-Down Unit (SDU),Alive,035-19511
200858,3353263,2743110,Male,35,African American,458,1106,"Embolus, pulmonary",182.9,03:22:00,...,Emergency Department,1,admit,100.8,100.8,20:38:00,928,Telemetry,Alive,035-22638

In [4]:
from src.preprocessing import *
diagnosis = get_df("diagnosis")
icd9_counts = diagnosis['icd9code'].value_counts()
print(icd9_counts.index[:5])
diagnosis

Index(['518.81, J96.00', '584.9, N17.9', '401.9, I10', '486, J18.9',
       '427.31, I48.0'],
      dtype='object', name='icd9code')

,diagnosisid,patientunitstayid,activeupondischarge,diagnosisoffset,diagnosisstring,icd9code,diagnosispriority
0,4222318,141168,False,72,cardiovascular|chest pain / ASHD|coronary arte...,"414.00, I25.10",Other
1,3370568,141168,True,118,cardiovascular|ventricular disorders|cardiomyo...,NaN,Other
2,4160941,141168,False,72,pulmonary|disorders of the airways|COPD,"491.20, J44.9",Other
3,4103261,141168,True,118,pulmonary|disorders of the airways|COPD,"491.20, J44.9",Other
4,3545241,141168,True,118,cardiovascular|ventricular disorders|congestiv...,"428.0, I50.9",Other
...,...,...,...,...,...,...,...
2710667,46330138,3353251,False,11304,renal|disorder of urinary tract / renal system...,"599.0, N39.0",Other
2710668,46150971,3353251,False,4080,cardiovascular|shock / hypotension|sepsis,"038.9, A41.9",Major
2710669,46259796,3353254,True,41,renal|disorder of kidney|acute renal failure|d...,"584.9, N17.9",Major
2710670,46204273,3353254,True,41,gastrointestinal|GI bleeding / PUD|lower GI bl...,"578.9, K92.2",Primary
2710671,46335124,3353263,True,100,pulmonary|disorders of vasculature|pulmonary e...,"415.19, I26.99",Other

In [5]:
code = '518.81, J96.00'
diagnosis[diagnosis['icd9code'] == code]['diagnosisstring'].unique()

array(['pulmonary|respiratory failure|acute respiratory failure',
       'pulmonary|respiratory failure|acute respiratory failure due to volume overload without CHF',
       'pulmonary|respiratory failure|acute respiratory failure|due to neurological process',
       'pulmonary|respiratory failure|acute respiratory failure|due to increased CO2 production',
       'pulmonary|respiratory failure|acute respiratory failure|due to pulmonary infiltrates',
       'pulmonary|respiratory failure|acute respiratory failure|due to chest wall deformity',
       'pulmonary|respiratory failure|acute respiratory failure|due to inability to clear secretions',
       'pulmonary|respiratory failure|acute respiratory failure|drug related',
       'pulmonary|respiratory failure|acute respiratory failure|drug related|benzodiazepine',
       'pulmonary|respiratory failure|acute respiratory failure|etiology unknown',
       'pulmonary|respiratory failure|acute respiratory failure|due to neurological process|spinal cord injury',
       'surgery|respiratory failure|ventilatory failure',
       'pulmonary|respiratory failure|acute respiratory failure|drug related|narcotic',
       'pulmonary|respiratory failure|acute respiratory failure|due to atelectasis',
       'pulmonary|respiratory failure|acute respiratory failure|due to neurological process|encephalopathy',
       'pulmonary|respiratory failure|acute respiratory failure|due to muscle weakness',
       'surgery|respiratory failure|ventilatory failure|drug related|residual general anesthesia',
       'surgery|respiratory failure|ventilatory failure|etiology unknown',
       'pulmonary|respiratory failure|acute respiratory failure|due to abdominal distention',
       'surgery|respiratory failure|ventilatory failure|due to muscle weakness',
       'pulmonary|respiratory failure|acute respiratory failure|due to pain',
       'surgery|respiratory failure|ventilatory failure|drug related',
       'pulmonary|respiratory failure|acute respiratory failure|due to neurological process|brain stem dysfunction',
       'surgery|respiratory failure|ventilatory failure|due to neurological process|encephalopathy',
       'pulmonary|respiratory failure|acute respiratory failure|drug related|barbiturate',
       'pulmonary|respiratory failure|acute respiratory failure|due to neurological process|myasthenia gravis',
       'pulmonary|respiratory failure|acute respiratory failure|due to neurological process|Guillain-Barre',
       'surgery|respiratory failure|ventilatory failure|due to atelectasis',
       'surgery|respiratory failure|ventilatory failure|due to pulmonary infiltrates',
       'surgery|respiratory failure|ventilatory failure|due to inability to clear secretions',
       'pulmonary|respiratory failure|acute respiratory failure|due to neurological process|phrenic nerve dysfunction',
       'surgery|respiratory failure|ventilatory failure|due to increased CO2 production',
       'surgery|respiratory failure|ventilatory failure|due to neurological process|myasthenia gravis',
       'surgery|respiratory failure|ventilatory failure|due to neurological process',
       'surgery|respiratory failure|ventilatory failure|due to neurological process|brain stem dysfunction'],
      dtype=object)

In [51]:
diagnosis.sort_values(by='diagnosisoffset')

,diagnosisid,patientunitstayid,activeupondischarge,diagnosisoffset,diagnosisstring,icd9code,diagnosispriority
1023906,21630378,1446964,False,-49755,pulmonary|disorders of the airways|COPD,"491.20, J44.9",Other
1023904,21326824,1446964,False,-49755,pulmonary|disorders of the airways|asthma / br...,"493.90, J45",Major
1023905,20878411,1446964,False,-49755,pulmonary|disorders of the airways|acute COPD ...,"491.21, J44.1",Primary
1023895,20658866,1446962,False,-47846,cardiovascular|arrhythmias|atrial fibrillation,"427.31, I48.0",Primary
1023894,21420334,1446962,False,-47846,pulmonary|disorders of the airways|acute COPD ...,"491.21, J44.1",Major
...,...,...,...,...,...,...,...
1461495,30972037,2747640,False,762801,pulmonary|respiratory failure|chronic respirat...,"518.83, J96.10",Other
1461166,34015146,2747640,True,764242,neurologic|trauma - CNS|intracranial injury|wi...,"852.00, S06.6",Other
1460591,33178685,2747640,True,764242,renal|disorder of kidney|ESRD (end stage renal...,"585.6, N18.6",Other
1458921,32131494,2747640,True,764242,pulmonary|respiratory failure|chronic respirat...,"518.83, J96.10",Other
1458806,32455553,2747640,True,764242,neurologic|altered mental status / pain|persis...,"780.03, R40.3",Primary

In [102]:
filtered_df = diagnosis[diagnosis['diagnosisstring'].str.contains('chlamydia')]
filtered_df

,diagnosisid,patientunitstayid,activeupondischarge,diagnosisoffset,diagnosisstring,icd9code,diagnosispriority
2505956,44337982,3134132,False,327,infectious diseases|chest/pulmonary infections...,"483.1, J16.0",Major
2505958,44291000,3134132,True,3072,infectious diseases|chest/pulmonary infections...,"483.1, J16.0",Major
2505981,44152443,3134132,False,1157,infectious diseases|chest/pulmonary infections...,"483.1, J16.0",Major
2506773,44393132,3134315,True,2725,pulmonary|pulmonary infections|pneumonia|commu...,"483.1, J16.0",Major
2506780,43912817,3134315,False,1644,pulmonary|pulmonary infections|pneumonia|commu...,"483.1, J16.0",Major
2536681,44088148,3143703,False,196,pulmonary|pulmonary infections|pneumonia|commu...,"483.1, J16.0",Major
2544160,44227332,3146253,False,88,pulmonary|pulmonary infections|pneumonia|hospi...,"483.1, J16.0",Major
2564621,44205033,3151567,False,166,pulmonary|pulmonary infections|pneumonia|commu...,"483.1, J16.0",Major
2564648,44298105,3151567,False,166,infectious diseases|chest/pulmonary infections...,"483.1, J16.0",Major
2570646,44069425,3153828,False,306,pulmonary|pulmonary infections|pneumonia|commu...,"483.1, J16.0",Major
2576147,44043080,3155894,False,3328,pulmonary|pulmonary infections|pneumonia|commu...,"483.1, J16.0",Major
2576209,43916289,3155894,False,4883,pulmonary|pulmonary infections|pneumonia|commu...,"483.1, J16.0",Major

In [37]:
nums = diagnosis['icd9code'].str.split(',').str[0]
nums = pd.to_numeric(nums, errors='coerce')
diagnosis[nums.between(800,999)]

,diagnosisid,patientunitstayid,activeupondischarge,diagnosisoffset,diagnosisstring,icd9code,diagnosispriority
297,4209572,141604,True,13,toxicology|drug overdose|ethanol overdose,"980.0, E980.2, T51.0",Primary
321,3533965,141751,True,460,cardiovascular|shock / hypotension|signs and s...,995.90,Other
330,3843817,141751,False,45,cardiovascular|shock / hypotension|signs and s...,995.90,Other
675,3823283,142388,False,1757,burns/trauma|trauma - chest|pneumothorax|tension,860.0,Other
681,3555254,142388,True,5961,burns/trauma|trauma - chest|pneumothorax|tension,860.0,Other
...,...,...,...,...,...,...,...
2710415,46100655,3353197,False,6586,cardiovascular|shock / hypotension|signs and s...,995.90,Major
2710436,46100634,3353197,False,24333,cardiovascular|shock / hypotension|signs and s...,995.90,Major
2710446,46100607,3353197,False,16916,cardiovascular|shock / hypotension|signs and s...,995.90,Major
2710447,46100343,3353197,False,9763,cardiovascular|shock / hypotension|signs and s...,995.90,Major
2710453,46100669,3353197,False,10988,cardiovascular|shock / hypotension|signs and s...,995.90,Major

In [3]:
from src.preprocessing import eICUData

all_hospitals = eICUData(verbose=True)
all_hospitals.data

Retrieving diagnosis...
Retrieving treatment...

/Users/Hanita/Projects/COMS4995:BINF4008-ML4HealthMed/ehr-ncm/src/preprocessing.py:108: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[item] = df[table + "string"].str.contains(item, case=False)

Retrieving vitalAperiodic...

Loading periodic vitals: 100%|██████████| 147/147 [00:51<00:00,  2.86it/s]

,uniquepid,hospitalid,mortality,age,gender,ethnicity,sepsis,diabetes,respiratory failure,renal failure,...,diuretic,hypertension|ACE inhibitor,hypertension|angiotensin II receptor blocker (ARB),azithromycin,clarithromycin,amoxicillin,bp,sao2,hr,respiration
0,002-34851,59,1.0,70,Female,Caucasian,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,85.500000,92.630684,109.114807,26.813433
1,002-33870,60,0.0,52,Female,Caucasian,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,86.500000,98.645164,91.225319,NaN
2,002-33870,60,0.0,52,Female,Caucasian,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,86.500000,98.645164,91.225319,NaN
3,002-5276,73,0.0,68,Male,Caucasian,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,68.833333,98.730690,85.401039,20.598959
4,002-37665,67,0.0,71,Male,Caucasian,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,94.571429,95.437279,82.989471,24.102474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262216,035-751,458,0.0,79,Female,Caucasian,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,102.173913,94.637100,91.040161,26.706827
262217,035-5166,458,0.0,73,Male,African American,1.0,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,83.111111,98.323341,73.570770,21.369707
262218,035-5166,458,0.0,73,Male,African American,1.0,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,83.111111,95.798065,80.118950,20.802109
262219,035-19511,459,0.0,81,Male,Caucasian,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,85.764706,98.321426,76.178574,22.226191
262220,035-22638,458,0.0,35,Male,African American,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,101.058824,97.548912,81.413040,19.483696

In [6]:
treatments = all_hospitals.settings.tables['treatment']
all_hospitals.data[treatments].sum()

vancomycin                                             21867.0
piperacillin                                           14501.0
cefepime                                                5481.0
meropenem                                               2836.0
insulin                                                54271.0
ventilation                                           128157.0
dialysis                                               20246.0
diuretic                                               28614.0
hypertension|ACE inhibitor                             37102.0
hypertension|angiotensin II receptor blocker (ARB)     34500.0
azithromycin                                            4171.0
clarithromycin                                            24.0
amoxicillin                                              255.0
dtype: float64

In [2]:
from src.preprocessing import eICUDataSettings

settings = eICUDataSettings("default")
settings.tables

{'diagnosis': ['sepsis',
  'diabetes',
  'respiratory failure',
  'renal failure',
  'hypertension',
  'pneumonia'],
 'treatment': {'sepsis': ['vancomycin',
   'piperacillin',
   'cefepime',
   'meropenem'],
  'diabetes': ['insulin'],
  'respiratory failure': ['ventilation'],
  'renal failure': ['dialysis'],
  'hypertension': ['diuretic',
   'hypertension|ACE inhibitor',
   'hypertension|angiotensin II receptor blocker (ARB)'],
  'pneumonia': ['azithromycin', 'clarithromycin', 'amoxicillin']},
 'vitalAperiodic': {'noninvasivemean': 'mean'},
 'vitalPeriodic': {'sao2': 'mean', 'heartrate': 'mean', 'respiration': 'mean'}}

In [8]:
from src.utils import *
treatment = get_df("treatment")
treatment

,treatmentid,patientunitstayid,treatmentoffset,treatmentstring,activeupondischarge
0,8399138,242040,198,cardiovascular|hypertension|angiotensin II rec...,False
1,8626134,242040,198,cardiovascular|myocardial ischemia / infarctio...,False
2,8517569,242040,198,infectious diseases|medications|therapeutic an...,False
3,9597686,242040,616,cardiovascular|non-operative procedures|diagno...,False
4,9334096,242040,618,infectious diseases|medications|therapeutic an...,True
...,...,...,...,...,...
3688740,82519717,3353251,291,pulmonary|radiologic procedures / bronchoscopy...,False
3688741,82608952,3353251,291,pulmonary|ventilation and oxygenation|mechanic...,False
3688742,82541591,3353254,41,cardiovascular|intravenous fluid|normal saline...,True
3688743,82230708,3353254,41,cardiovascular|intravenous fluid|blood product...,True
3688744,82479989,3353263,100,pulmonary|medications|anticoagulant administra...,True

In [9]:
treatment['treatmentstring'].value_counts()

treatmentstring
pulmonary|ventilation and oxygenation|mechanical ventilation                                            117481
pulmonary|radiologic procedures / bronchoscopy|chest x-ray                                               65148
neurologic|pain / agitation / altered mentation|analgesics|narcotic analgesic                            46055
renal|urinary catheters|foley catheter                                                                   40672
cardiovascular|intravenous fluid|normal saline administration                                            40522
                                                                                                         ...
toxicology|drug overdose|agent specific therapy|cocaine overdose|beta-blockers|labetalol                     1
pulmonary|medications|antibacterials|third generation cephalosporin|cefixime                                 1
toxicology|drug overdose|mechanical ventilation|volume assured                                               1
pulmonary|surgery / incision and drainage of thorax|thoracoscopic procedure|saddle pulmonary embolus         1
surgery|pulmonary therapies|mechanical ventilation|non-invasive ventilation|nasal mask                       1
Name: count, Length: 2711, dtype: int64

In [17]:
treatment[treatment['treatmentstring'].str.contains('piperacillin')]['treatmentstring'].unique()

array(['infectious diseases|medications|therapeutic antibacterials|penicillins|piperacillin/tazobactam',
       'pulmonary|medications|antibacterials|penicillins|piperacillin/tazobactam',
       'surgery|infection|therapeutic antibacterials|penicillins|piperacillin/tazobactam',
       'infectious diseases|medications|therapeutic antibacterials|penicillins|piperacillin',
       'cardiovascular|other therapies|antibacterials|penicillins|piperacillin/tazobactam',
       'pulmonary|medications|antibacterials|penicillins|piperacillin',
       'cardiovascular|other therapies|antibacterials|penicillins|piperacillin',
       'surgery|infection|therapeutic antibacterials|penicillins|piperacillin'],
      dtype=object)

In [22]:
data = all_hospitals.data.merge(
    all_hospitals.id_map,
    on=["uniquepid", "hospitalid"],
    how="left"
)
sepsis = data[data['sepsis'] == 1]
sepsis

,uniquepid,hospitalid,mortality,age,gender,ethnicity,sepsis,diabetes,respiratory failure,renal failure,hypertension,pneumonia,atrial fibrillation,noninvasivemean,sao2,hr,respiration,patientunitstayid
14,002-21459,60,0.0,82,Male,Caucasian,1.0,0.0,0.0,0.0,0.0,0.0,0.0,80.305882,95.050957,111.057404,33.486404,141227
50,002-67735,67,0.0,61,Female,Caucasian,1.0,0.0,1.0,0.0,0.0,1.0,0.0,113.186047,95.935135,83.371635,21.845493,141288
51,002-67735,67,0.0,61,Female,Caucasian,1.0,0.0,1.0,0.0,0.0,1.0,0.0,113.186047,95.935135,83.371635,21.845493,141289
52,002-67735,67,0.0,61,Female,Caucasian,1.0,0.0,1.0,0.0,0.0,1.0,0.0,113.186047,95.935135,83.371635,21.845493,237402
53,002-67735,67,0.0,61,Female,Caucasian,1.0,0.0,1.0,0.0,0.0,1.0,0.0,113.186047,95.935135,83.371635,21.845493,237403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715088,035-5166,458,0.0,73,Male,African American,1.0,0.0,1.0,1.0,0.0,1.0,0.0,83.111111,98.323341,73.570770,21.369707,3337093
715089,035-5166,458,0.0,73,Male,African American,1.0,0.0,1.0,1.0,0.0,1.0,0.0,83.111111,98.323341,73.570770,21.369707,3353251
715090,035-5166,458,0.0,73,Male,African American,1.0,0.0,1.0,1.0,0.0,1.0,0.0,83.111111,95.798065,80.118950,20.802109,3337092
715091,035-5166,458,0.0,73,Male,African American,1.0,0.0,1.0,1.0,0.0,1.0,0.0,83.111111,95.798065,80.118950,20.802109,3337093
715092,035-5166,458,0.0,73,Male,African American,1.0,0.0,1.0,1.0,0.0,1.0,0.0,83.111111,95.798065,80.118950,20.802109,3353251

In [60]:
def get_treatments_for(diagnosis):
    diagnosed = data[data[diagnosis]==1]
    return treatment[treatment['patientunitstayid'].isin(diagnosed['patientunitstayid'])]['treatmentstring'].value_counts()

sepsis_treatments = get_treatments_for('sepsis')
sepsis_treatments[sepsis_treatments.index.str.contains('antibacterials', case=False)][:20]

treatmentstring
infectious diseases|medications|therapeutic antibacterials|vancomycin                                    18079
infectious diseases|medications|therapeutic antibacterials                                               17963
infectious diseases|medications|therapeutic antibacterials|penicillins|piperacillin/tazobactam           10763
infectious diseases|medications|therapeutic antibacterials|quinolone|levofloxacin                         5967
pulmonary|medications|antibacterials                                                                      5414
infectious diseases|medications|therapeutic antibacterials|third generation cephalosporin|ceftriaxone     5058
infectious diseases|medications|therapeutic antibacterials|fourth generation cephalosporin|cefepime       4492
infectious diseases|medications|therapeutic antibacterials|metronidazole                                  4393
infectious diseases|medications|therapeutic antibacterials|empiric antibacterial coverage                 3413
infectious diseases|medications|therapeutic antibacterials|carbapenem|meropenem                           2830
pulmonary|medications|antibacterials|vancomycin                                                           2755
infectious diseases|medications|therapeutic antibacterials|macrolide|azithromycin                         2082
pulmonary|medications|antibacterials|penicillins|piperacillin/tazobactam                                  1945
infectious diseases|medications|prophylactic antibacterials                                               1700
pulmonary|medications|antibacterials|quinolone|levofloxacin                                               1357
infectious diseases|medications|therapeutic antibacterials|linezolid                                      1022
infectious diseases|medications|therapeutic antibacterials|carbapenem|imipenem-cilastatin                  961
pulmonary|medications|antibacterials|third generation cephalosporin|ceftriaxone                            940
infectious diseases|medications|therapeutic antibacterials|carbapenem|ertapenem                            826
infectious diseases|medications|therapeutic antibacterials|penicillins                                     811
Name: count, dtype: int64

In [41]:
get_treatments_for('pneumonia')[:10]

treatmentstring
pulmonary|ventilation and oxygenation|mechanical ventilation                     39154
pulmonary|radiologic procedures / bronchoscopy|chest x-ray                       24150
pulmonary|medications|bronchodilator                                             16801
renal|urinary catheters|foley catheter                                           16169
infectious diseases|medications|therapeutic antibacterials                       15833
infectious diseases|medications|therapeutic antibacterials|vancomycin            14817
pulmonary|consultations|Pulmonary/CCM consultation                               14598
infectious diseases|cultures / immuno-assays|cultures                            13949
neurologic|pain / agitation / altered mentation|analgesics|narcotic analgesic    13621
endocrine|glucose metabolism|insulin                                             13370
Name: count, dtype: int64

In [61]:
treatment[treatment['treatmentstring'].str.contains('ACE inhibitor')]['treatmentstring'].unique()

array(['cardiovascular|hypertension|ACE inhibitor|lisinopril',
       'cardiovascular|myocardial ischemia / infarction|ACE inhibitor|lisinopril',
       'cardiovascular|hypertension|ACE inhibitor|enalapril|IV',
       'cardiovascular|hypertension|ACE inhibitor|enalapril',
       'cardiovascular|ventricular dysfunction|ACE inhibitor|quinapril',
       'cardiovascular|myocardial ischemia / infarction|ACE inhibitor',
       'cardiovascular|myocardial ischemia / infarction|ACE inhibitor|ramipril',
       'cardiovascular|hypertension|ACE inhibitor|captopril',
       'cardiovascular|hypertension|ACE inhibitor|quinapril',
       'cardiovascular|hypertension|ACE inhibitor',
       'cardiovascular|ventricular dysfunction|ACE inhibitor|lisinopril',
       'cardiovascular|myocardial ischemia / infarction|ACE inhibitor|enalapril',
       'cardiovascular|hypertension|ACE inhibitor|benazepril',
       'cardiovascular|hypertension|ACE inhibitor|enalapril|oral',
       'cardiovascular|hypertension|ACE inhibitor|ramipril',
       'cardiovascular|ventricular dysfunction|ACE inhibitor|enalapril|IV',
       'cardiovascular|myocardial ischemia / infarction|ACE inhibitor|enalapril|IV',
       'cardiovascular|ventricular dysfunction|ACE inhibitor',
       'surgery|cardiac therapies|ACE inhibitor|lisinopril',
       'cardiovascular|myocardial ischemia / infarction|ACE inhibitor|enalapril|oral',
       'cardiovascular|hypertension|ACE inhibitor|fosinopril',
       'cardiovascular|myocardial ischemia / infarction|ACE inhibitor|fosinopril',
       'surgery|cardiac therapies|ACE inhibitor',
       'cardiovascular|ventricular dysfunction|ACE inhibitor|enalapril',
       'cardiovascular|ventricular dysfunction|ACE inhibitor|ramipril',
       'cardiovascular|myocardial ischemia / infarction|ACE inhibitor|captopril',
       'surgery|cardiac therapies|ACE inhibitor|captopril',
       'cardiovascular|ventricular dysfunction|ACE inhibitor|enalapril|oral',
       'cardiovascular|ventricular dysfunction|ACE inhibitor|captopril',
       'cardiovascular|myocardial ischemia / infarction|ACE inhibitor|benazepril',
       'surgery|cardiac therapies|ACE inhibitor|enalapril',
       'surgery|cardiac therapies|ACE inhibitor|enalapril|IV',
       'surgery|cardiac therapies|ACE inhibitor|quinapril',
       'surgery|cardiac therapies|ACE inhibitor|ramipril'], dtype=object)

In [46]:
treatment[treatment['treatmentstring'].str.contains('renal failure')]['treatmentstring'].unique()

array(['renal|dialysis|hemodialysis|for chronic renal failure',
       'renal|dialysis|hemodialysis|for acute renal failure',
       'renal|dialysis|peritoneal dialysis|for chronic renal failure',
       'renal|dialysis|ultrafiltration (fluid removal only)|for acute renal failure',
       'renal|dialysis|ultrafiltration (fluid removal only)|for chronic renal failure',
       'renal|dialysis|peritoneal dialysis|for acute renal failure'],
      dtype=object)

In [64]:
agg_dict = {"hr": "mean"}
df = (
    all_hospitals.data
    .groupby(["hospitalid"])
    .agg(agg_dict)
    .reset_index()
)
df

     hospitalid         hr
0            56  81.737686
1            58  82.940857
2            59  83.765640
3            60  83.586418
4            61  84.958061
..          ...        ...
203         447  81.284683
204         449  82.921959
205         452  83.512703
206         458  83.097664
207         459  85.708252

[208 rows x 2 columns]

In [67]:
df.rename(columns={'h r': 'new_name'})

     hospitalid         hr
0            56  81.737686
1            58  82.940857
2            59  83.765640
3            60  83.586418
4            61  84.958061
..          ...        ...
203         447  81.284683
204         449  82.921959
205         452  83.512703
206         458  83.097664
207         459  85.708252

[208 rows x 2 columns]

In [9]:
vitalper_len = 0
pbar = tqdm(pd.read_csv(
    "physionet.org/files/eicu-crd/2.0/vitalPeriodic.csv.gz",
    compression="gzip",
    chunksize=1_000_000,
    usecols=["patientunitstayid", "sao2", "heartrate", "respiration"],
    dtype={"patientunitstayid": 'int32', "sao2": 'float32', "heartrate": 'float32', "respiration": 'float32'},
), desc="Loading periodic vitals")

for chunk in pbar:
    vitalper_len += len(chunk)
    pbar.set_postfix(vitalper_len=vitalper_len)

vitalper_len

Loading periodic vitals: 147it [00:37,  3.88it/s, vitalper_len=1.47e+8]

146671642

In [3]:
import json 
with open('configs/default.json', 'r') as file:
    data = json.load(file)

data

{'demographics': ['age', 'gender', 'ethnicity'],
 'tables': {'diagnosis': ['sepsis', 'diabetes'],
  'vitalAperiodic': {'noninvasivemean': 'mean'},
  'vitalPeriodic': {'sao2': 'mean',
   'heartrate': 'mean',
   'respiration': 'mean'}}}

In [9]:
data.get("hospitals")

In [12]:
["patientunitstayid"] + data.keys()

TypeError: can only concatenate list (not "builtin_function_or_method") to list

In [8]:
tables = {}
print(tables.get("diagnoses"), " .")

None  .